name: my_first_project

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  intl: ^0.20.2
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
